# FLoRA Preparation Pipeline
# Download, deduplicate, and prepare paper-level dataset (Replications + Reproductions)
# FORRT Team

# ---- Setup ----
library(dplyr)
library(stringr)
library(tibble)
library(readxl)
library(jsonlite)
library(glue)
library(httr)
library(readr)

if (!file.exists(here::here("R", "cache_config.R"))) {
  stop("Cannot find cache config. Ensure you're in the project or run from repo root.")
}

source(here::here("R", "cache_config.R"))
source(here::here("R", "augmentation.R"))
source(here::here("R", "crossref_cache.R"))
source(here::here("R", "openalex_cache.R"))
source(here::here("R", "llm_classification.R"))
source(here::here("R", "unpaywall_cache.R"))
source(here::here("R", "preprint_dedup.R"))
source(here::here("R", "cos_quote_rewrite.R"))

# ---- Configuration ----
FReD_FOUNDATION_SUCCESS_CODING <- "https://docs.google.com/spreadsheets/d/1J9Lp_RF6hqlDlLT3aMW3zvbQ3GYGbmFzZYdFc7XXwhc/export?gid=984458430&format=csv"
REPLICATION_GSHEET_URL         <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vT0VnLyrf9GCYXtN6l1DgaoLlg6H5r-08Op9eJzSripS1QBSHL031Arc27yUDe0YY7cB4TOnYMm2Vh1/pub?gid=863031634&single=true&output=csv"
REPRODUCTION_GSHEET_URL        <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vT0VnLyrf9GCYXtN6l1DgaoLlg6H5r-08Op9eJzSripS1QBSHL031Arc27yUDe0YY7cB4TOnYMm2Vh1/pub?gid=984458430&single=true&output=csv"
EXCLUSIONS_GSHEET_URL          <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vT0VnLyrf9GCYXtN6l1DgaoLlg6H5r-08Op9eJzSripS1QBSHL031Arc27yUDe0YY7cB4TOnYMm2Vh1/pub?gid=1098183075&single=true&output=csv"
SCORE_URL                      <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vSlPVImL7kjzMfpfX08JtAikvEiBg8uQ3HyEJs-YvuQMUa2RMvip-4v8-DilWl2PdwOD_UTD8gJ5wKA/pub?gid=1421575264&single=true&output=csv"
FLORA_OUTPUT                   <- here::here("output", "flora.csv")

# ╔══════════════════════════════════════════════════════════════════╗
# ║  Validated-DB CSV URL                                           ║
# ║  Generated by export_validated.py in the flora-validation repo. ║
# ║  Update this URL after each export + commit + push.            ║
# ╚══════════════════════════════════════════════════════════════════╝
VALIDATED_CSV_URL <- "https://raw.githubusercontent.com/HamidBehbood/flora-validation/main/data/validated_export.csv"

cat("\n=== FLoRA Preparation Pipeline ===\n")

# ---- Download FLoRA Data (Replications + Reproductions) ----
replications <- tryCatch({
  read_csv(REPLICATION_GSHEET_URL, show_col_types = FALSE)
}, error = function(e) {
  stop("Failed to download replications data. Check URL and network connection.\n",
       "Error: ", e$message)
})
cat(sprintf("    ✓ Downloaded %d replication rows × %d columns\n", nrow(replications), ncol(replications)))

replications <- replications %>%
  filter(validation_status %in% c("validated - chosen", "validated - changed", "validated - unchanged"))
cat(sprintf("    ✓ Filtered to %d validated replications\n", nrow(replications)))

reproductions <- tryCatch({
  read_csv(REPRODUCTION_GSHEET_URL, show_col_types = FALSE)
}, error = function(e) {
  stop("Failed to download reproductions data. Check URL and network connection.\n",
       "Error: ", e$message)
})
cat(sprintf("    ✓ Downloaded %d reproduction rows × %d columns\n", nrow(reproductions), ncol(reproductions)))

reproductions <- reproductions %>%
  filter(validation %in% c("validated - chosen", "validated - changed", "validated - unchanged"))
cat(sprintf("    ✓ Filtered to %d validated reproductions\n", nrow(reproductions)))

tag_source <- function(df, type_label, source_label) {
  df %>%
    rename_with(~ "outcome_quote_source", any_of("out_quote_source")) %>%
    mutate(type = type_label, source = source_label)
}

if (nrow(reproductions) == 0) {
  flora_raw <- tag_source(replications, "replication", "replications")
} else if (nrow(replications) == 0) {
  flora_raw <- tag_source(reproductions, "reproduction", "reproductions")
} else {
  flora_raw <- bind_rows(
    tag_source(replications, "replication", "replications"),
    tag_source(reproductions, "reproduction", "reproductions")
  )
}

# ---- Add COS source data ----
replications_cos <- read_csv(FReD_FOUNDATION_SUCCESS_CODING, show_col_types = FALSE, skip = 1)
cat(sprintf("    ✓ Downloaded %d COS rows\n", nrow(replications_cos)))

replications_cos <- replications_cos %>%
  filter(validation %in% c("validated - chosen", "validated - changed", "validated - unchanged"))
cat(sprintf("    ✓ Filtered to %d validated COS entries\n", nrow(replications_cos)))

replications_cos <- replications_cos %>%
  mutate(outcome_quote = rewrite_cos_quote(outcome_quote))
cat(sprintf("    ✓ Rewrote %d shorthand outcome quotes\n",
            sum(str_detect(replications_cos$outcome_quote,
                           "^Coded as |^Replicated = |^Rep\\. (s1|s2|s1\\+s2) = |^95% CI for the meta-analytic |^Subjective replication success rating |^Classified as mixed:|^Outcome classified as "),
                na.rm = TRUE)))

replications_cos <- replications_cos %>%
  mutate(repl_id = coalesce(url_r, doi_r)) %>%
  group_by(doi_o, repl_id) %>%
  summarise(
    ref_o                = first(ref_o),
    ref_r                = first(ref_r),
    url_r                = first(url_r),
    doi_r                = first(doi_r),
    abstract_r           = first(abstract_r),
    outcome              = if (length(unique(outcome)) == 1) unique(outcome) else "mixed",
    outcome_quote        = paste(unique(na.omit(outcome_quote)), collapse = " || "),
    outcome_quote_source = paste(unique(na.omit(out_quote_source)), collapse = " || "),
    type                 = "replication",
    source               = "COS",
    .groups              = "drop"
  )
cat(sprintf("    ✓ Processed %d COS replication rows × %d columns\n", nrow(replications_cos), ncol(replications_cos)))

flora_raw <- bind_rows(flora_raw, replications_cos)

# ---- Add SCORE data ----
cat("\n### SCORE Integration\n")
score_data <- tryCatch({
  read_csv(SCORE_URL, show_col_types = FALSE)
}, error = function(e) {
  stop("Failed to download SCORE data. Check URL and network connection.\n",
       "Error: ", e$message)
})
cat(sprintf("✓ Loaded SCORE data: %d rows\n", nrow(score_data)))

score_prepared <- score_data %>%
  rename(outcome_quote_source = out_quote_source) %>%
  mutate(type = "replication", source = "SCORE") %>%
  select(-any_of("link_r"))

common_cols <- intersect(names(flora_raw), names(score_prepared))
cat(sprintf("  Common columns: %d\n", length(common_cols)))

flora_raw <- bind_rows(flora_raw, score_prepared %>% select(all_of(common_cols)))
cat(sprintf("✓ Merged with FLoRA data\n"))
cat(sprintf("  Total rows after SCORE merge: %d\n", nrow(flora_raw)))

# ╔══════════════════════════════════════════════════════════════════╗
# ║  [NEW SOURCE]  Validated Database CSV                           ║
# ║                                                                  ║
# ║  Reads validated_export.csv generated by export_validated.py   ║
# ║  in the flora-validation repo and committed to GitHub.          ║
# ║                                                                  ║
# ║  MERGE STRATEGY                                                  ║
# ║    GSheet rows are already in flora_raw and go first →          ║
# ║    dedup below keeps the GSheet version on conflict.            ║
# ║                                                                  ║
# ║  REFERENCES                                                      ║
# ║    doi_r / doi_o are passed to get_references() in Step 6b so   ║
# ║    OpenAlex / Crossref fills ref_o and ref_r automatically —    ║
# ║    no manual DB connection needed in R.                         ║
# ╚══════════════════════════════════════════════════════════════════╝
cat("\n### Validated Database CSV Merge\n")

validated_source <- tryCatch({
  result <- read_csv(VALIDATED_CSV_URL, show_col_types = FALSE) %>%
    mutate(validated_db_row = TRUE)
  cat(sprintf("    ✓ Loaded %d rows from validated CSV\n", nrow(result)))
  result
}, error = function(e) {
  warning("Could not load validated CSV — skipping this source.\n",
          "Error: ", e$message)
  NULL
})

# Stamp marker on all pre-existing rows so select(all_of(flora_cols)) never fails.
flora_raw$validated_db_row <- FALSE

if (!is.null(validated_source) && nrow(validated_source) > 0) {
  # GSheet rows first in flora_raw → they win deduplication.
  flora_raw <- bind_rows(flora_raw, validated_source)
  cat(sprintf("    ✓ %d validated rows appended\n",
              sum(flora_raw$validated_db_row, na.rm = TRUE)))
  cat(sprintf("    ✓ flora_raw total after validated merge: %d rows\n", nrow(flora_raw)))
} else {
  cat("    ℹ  No validated rows added (CSV unavailable or empty)\n")
}

# ---- Apply Exclusions ----
exclusions <- tryCatch({
  read_csv(EXCLUSIONS_GSHEET_URL, show_col_types = FALSE)
}, error = function(e) {
  warning("Failed to download exclusions. Proceeding without exclusions.\n", e$message)
  tibble(doi_r = character(), url_r = character(), reason = character())
})
cat(sprintf("    ✓ Downloaded %d exclusions\n", nrow(exclusions)))

pre_exclusion <- nrow(flora_raw)
flora_raw <- flora_raw %>%
  filter(
    !(doi_r %in% exclusions$doi_r[!is.na(exclusions$doi_r)]) &
    !(url_r %in% exclusions$url_r[!is.na(exclusions$url_r)])
  )
cat(sprintf("    ✓ Excluded %d rows based on exclusion list\n", pre_exclusion - nrow(flora_raw)))

manual_exclusion_dois <- c(
  "10.31234/osf.io/jfmsz",
  "10.1177/0956797619831612",
  "korbmacher_2022"
)
manual_exclusion_urls <- c(
  "https://replications.clearerthinking.org/replication-2022psci33-8"
)

pre_manual <- nrow(flora_raw)
flora_raw <- flora_raw %>%
  filter(
    !tolower(doi_r) %in% tolower(manual_exclusion_dois) &
    !tolower(url_r) %in% tolower(manual_exclusion_urls)
  )
cat(sprintf("    ✓ Excluded %d rows based on manual exclusion list\n", pre_manual - nrow(flora_raw)))

# ---- Data Preparation ----
flora_cols <- c("doi_o", "ref_o", "url_o",
                "doi_r", "ref_r", "url_r",
                "abstract_r", "outcome", "outcome_quote", "outcome_quote_source", "type", "source",
                "validated_db_row")   # carried through pipeline; dropped at Step 10

clean_doi <- function(x) {
  x <- tolower(trimws(as.character(x)))
  x <- gsub("^(https?://)?(dx\\.)?doi\\.org/", "", x)
  x <- gsub("^doi:\\s*", "", x)
  x <- sub("\\s*digital\\s*object\\s*identifier.*$", "", x)
  x <- sub("\\s*get\\s*rights\\s*and\\s*content.*$", "", x)
  x <- sub("\\s.*$", "", x)
  x <- trimws(x)
  dplyr::na_if(x, "")
}

flora_data <- flora_raw %>%
  select(all_of(flora_cols)) %>%
  mutate(
    doi_o = clean_doi(doi_o),
    doi_r = clean_doi(doi_r)
  ) %>%
  mutate(
    url_r = if_else(
      !is.na(doi_r) & str_detect(tolower(url_r), if_else(is.na(doi_r), fixed("dummy_val"), fixed(doi_r))),
      NA_character_, url_r)
  )

# ---- Deduplication ----
pre_dedup <- nrow(flora_data)

norm_url <- function(x) {
  x <- tolower(trimws(as.character(x)))
  x <- gsub("^https?://", "", x)
  x <- gsub("^www\\.", "", x)
  x <- gsub("/+$", "", x)
  dplyr::na_if(x, "")
}

flora_data <- flora_data %>%
  mutate(url_r_norm = norm_url(url_r)) %>%
  distinct(doi_o, coalesce(url_r_norm, doi_r), .keep_all = TRUE) %>%
  select(-url_r_norm)

flora_data <- merge_doi_pair_dups(flora_data, verbose = TRUE)
post_dedup <- nrow(flora_data)
cat(sprintf("✓ Removed %d duplicate rows\n", post_dedup - pre_dedup))

dup_check <- flora_data %>%
  filter(!is.na(ref_r), ref_r != "") %>%
  group_by(doi_o, tolower(trimws(ref_r))) %>%
  filter(n() > 1) %>%
  ungroup()
if (nrow(dup_check) > 0) {
  cat(sprintf("⚠ WARNING: %d rows have same doi_o + ref_r but different identifiers:\n", nrow(dup_check)))
  dup_check %>% select(doi_o, doi_r, url_r, ref_r) %>% print(n = 20)
}

dup_check2 <- flora_data %>%
  filter(!is.na(doi_r), !is.na(url_r)) %>%
  mutate(url_r_norm = norm_url(url_r),
         doi_as_url = norm_url(paste0("doi.org/", doi_r))) %>%
  inner_join(
    flora_data %>%
      filter(!is.na(url_r), is.na(doi_r)) %>%
      mutate(url_r_norm = norm_url(url_r)) %>%
      select(doi_o, url_r_norm_other = url_r_norm, url_r_other = url_r),
    by = "doi_o"
  ) %>%
  filter(url_r_norm == url_r_norm_other | doi_as_url == url_r_norm_other)
if (nrow(dup_check2) > 0) {
  cat(sprintf("⚠ WARNING: %d rows may be duplicates (doi_r and url_r point to same resource):\n", nrow(dup_check2)))
  dup_check2 %>% select(doi_o, doi_r, url_r, url_r_other) %>% print(n = 20)
}

# ---- Step 5: DOI Validation ----
flora_data <- flora_data %>%
  mutate(
    doi_o_valid = is.na(doi_o) | str_starts(tolower(doi_o), "10."),
    doi_r_valid = is.na(doi_r) | str_starts(tolower(doi_r), "10.")
  )

invalid_indices <- !flora_data$doi_o_valid
invalid_o <- sum(invalid_indices)
if (invalid_o > 0) {
  show_all  <- invalid_o < 10
  n_to_show <- if (show_all) invalid_o else 5
  vals      <- head(flora_data$doi_o[invalid_indices], n_to_show)
  label     <- if (show_all) "Invalid doi_o values:" else "Example invalid doi_o values:"
  cat(sprintf("⚠ Found %d invalid doi_o values\n", invalid_o),
      paste(label, paste(vals, collapse = ", ")), "\n")
}

invalid_indices <- !flora_data$doi_r_valid
invalid_r <- sum(invalid_indices)
if (invalid_r > 0) {
  show_all  <- invalid_r < 10
  n_to_show <- if (show_all) invalid_r else 5
  vals      <- head(flora_data$doi_r[invalid_indices], n_to_show)
  label     <- if (show_all) "Invalid doi_r values:" else "Example invalid doi_r values:"
  cat(sprintf("⚠ Found %d invalid doi_r values\n", invalid_r),
      paste(label, paste(vals, collapse = ", ")), "\n")
}

flora_data <- flora_data %>% select(-doi_o_valid, -doi_r_valid)

# ---- Step 6a: Apply confirmed preprint-publication deduplication ----
flora_data <- apply_confirmed_preprint_dedup(flora_data, verbose = TRUE)

# ---- Step 6b: Fetch DOI References (APA + BibTeX) ----
# Includes DOIs from the validated CSV rows — OpenAlex fills ref_o / ref_r automatically.
unique_dois <- unique(tolower(c(flora_data$doi_o, flora_data$doi_r)))
unique_dois <- unique_dois[!is.na(unique_dois)]
refs <- get_references(unique_dois)

# ---- Step 7: Add clean References and Individual Fields ----
flora_augmented <- flora_data %>%
  left_join(
    refs %>% rename(
      doi_o = doi, ref_o_clean = reference_apa, bibtex_o = reference_bibtex,
      title_o = title, author_o = author, journal_o = journal,
      year_o = year, volume_o = volume, issue_o = issue, pages_o = pages
    ),
    by = "doi_o"
  ) %>%
  left_join(
    refs %>% rename(
      doi_r = doi, ref_r_clean = reference_apa, bibtex_r = reference_bibtex,
      title_r = title, author_r = author, journal_r = journal,
      year_r = year, volume_r = volume, issue_r = issue, pages_r = pages
    ),
    by = "doi_r"
  ) %>%
  mutate(
    ref_o = coalesce(ref_o_clean, ref_o),
    ref_r = coalesce(ref_r_clean, ref_r)
  )

has_text     <- function(x) !is.na(x) & nzchar(trimws(as.character(x)))
count_missing <- function(x) sum(!has_text(x))
count_present <- function(x) sum(has_text(x))

cat(sprintf("✓ Added clean references (APA + BibTeX) and individual fields\n"))
cat("\n--- Step 7 stats (BEFORE manual/BibTeX recovery) ---\n")
cat(sprintf("Rows: %d\n", nrow(flora_augmented)))
cat(sprintf("APA present:    %d original, %d replication\n", count_present(flora_augmented$ref_o_clean), count_present(flora_augmented$ref_r_clean)))
cat(sprintf("APA missing:    %d original, %d replication\n", count_missing(flora_augmented$ref_o_clean), count_missing(flora_augmented$ref_r_clean)))
cat(sprintf("BibTeX present: %d original, %d replication\n", count_present(flora_augmented$bibtex_o),    count_present(flora_augmented$bibtex_r)))
cat(sprintf("BibTeX missing: %d original, %d replication\n", count_missing(flora_augmented$bibtex_o),    count_missing(flora_augmented$bibtex_r)))
cat(sprintf("Title present:  %d original, %d replication\n", count_present(flora_augmented$title_o),     count_present(flora_augmented$title_r)))
cat(sprintf("Title missing:  %d original, %d replication\n", count_missing(flora_augmented$title_o),     count_missing(flora_augmented$title_r)))
cat("  Consider adding missing refs to manual_references.xlsx\n")

cat("\n### Step 7b: Manual URL overrides + BibTeX title recovery (R)\n")
before_title_r_missing <- count_missing(flora_augmented$title_r)
before_ref_r_missing   <- count_missing(flora_augmented$ref_r_clean)
before_bib_r_missing   <- count_missing(flora_augmented$bibtex_r)

flora_augmented <- augment_with_manual_url_refs_r(flora_augmented, verbose = TRUE)
flora_augmented <- augment_with_manual_url_refs(flora_augmented, side = "o", verbose = TRUE)
flora_augmented <- augment_with_openalex_url_refs_r(flora_augmented, verbose = TRUE)
flora_augmented <- synthesise_missing_refs_from_fields(flora_augmented, side = "r", verbose = TRUE)
flora_augmented <- synthesise_missing_refs_from_fields(flora_augmented, side = "o", verbose = TRUE)

cat("\n--- Step 7 stats (AFTER manual/BibTeX recovery) ---\n")
cat(sprintf("Rows: %d\n", nrow(flora_augmented)))
cat(sprintf("APA present:    %d original, %d replication\n", count_present(flora_augmented$ref_o_clean), count_present(flora_augmented$ref_r_clean)))
cat(sprintf("APA missing:    %d original, %d replication\n", count_missing(flora_augmented$ref_o_clean), count_missing(flora_augmented$ref_r_clean)))
cat(sprintf("BibTeX present: %d original, %d replication\n", count_present(flora_augmented$bibtex_o),    count_present(flora_augmented$bibtex_r)))
cat(sprintf("BibTeX missing: %d original, %d replication\n", count_missing(flora_augmented$bibtex_o),    count_missing(flora_augmented$bibtex_r)))
cat(sprintf("Title present:  %d original, %d replication\n", count_present(flora_augmented$title_o),     count_present(flora_augmented$title_r)))
cat(sprintf("Title missing:  %d original, %d replication\n", count_missing(flora_augmented$title_o),     count_missing(flora_augmented$title_r)))
cat("\nRecovered on R side (replication/reproduction):\n")
cat(sprintf("  title_r recovered:  %d\n", before_title_r_missing - count_missing(flora_augmented$title_r)))
cat(sprintf("  apa ref recovered:  %d\n", before_ref_r_missing   - count_missing(flora_augmented$ref_r_clean)))
cat(sprintf("  bibtex recovered:   %d\n", before_bib_r_missing   - count_missing(flora_augmented$bibtex_r)))

# ---- Step 7c: Clean text fields ----
flora_augmented <- clean_flora_text_fields(flora_augmented, verbose = TRUE)

# ---- Step 7d: Resolve preprint-publication duplicates ----
flora_augmented <- resolve_preprint_dedup(flora_augmented, verbose = TRUE)

# ---- Step 8: Add Privacy-Preserving IDs ----
flora_augmented <- flora_augmented %>%
  mutate(
    doi_o_hash = as.character(substr(openssl::md5(doi_o), 1, 3)),
    doi_r_hash = as.character(substr(openssl::md5(doi_r), 1, 3))
  )
cat(sprintf("  Unique original hashes:    %d\n", n_distinct(flora_augmented$doi_o_hash, na.rm = TRUE)))
cat(sprintf("  Unique replication hashes: %d\n", n_distinct(flora_augmented$doi_r_hash, na.rm = TRUE)))

# ---- Step 9: Add Language from OpenAlex ----
cat("\n### Step 9: Adding language from OpenAlex\n")
openalex_mailto <- Sys.getenv("OPENALEX_MAILTO", NA_character_)

if (!"language_o" %in% names(flora_augmented)) flora_augmented <- flora_augmented %>% mutate(language_o = NA_character_)
if (!"language_r" %in% names(flora_augmented)) flora_augmented <- flora_augmented %>% mutate(language_r = NA_character_)

dois_to_fetch_o <- flora_augmented %>% filter(!is.na(doi_o), is.na(language_o)) %>% pull(doi_o) %>% unique()
dois_to_fetch_r <- flora_augmented %>% filter(!is.na(doi_r), is.na(language_r)) %>% pull(doi_r) %>% unique()
cat(sprintf("Fetching language for %d original DOIs and %d replication DOIs...\n",
            length(dois_to_fetch_o), length(dois_to_fetch_r)))

if (length(dois_to_fetch_o) > 0) {
  meta_o <- get_openalex_language(dois_to_fetch_o, mailto = openalex_mailto)
  meta_o <- meta_o[!is.na(meta_o$doi), ]
  flora_augmented <- flora_augmented %>%
    left_join(meta_o %>% rename(doi_o = doi, language_o_new = language), by = "doi_o") %>%
    mutate(language_o = coalesce(language_o, language_o_new)) %>%
    select(-language_o_new)
}

if (length(dois_to_fetch_r) > 0) {
  meta_r <- get_openalex_language(dois_to_fetch_r, mailto = openalex_mailto)
  meta_r <- meta_r[!is.na(meta_r$doi), ]
  flora_augmented <- flora_augmented %>%
    left_join(meta_r %>% rename(doi_r = doi, language_r_new = language), by = "doi_r") %>%
    mutate(language_r = coalesce(language_r, language_r_new)) %>%
    select(-language_r_new)
}

cat(sprintf("  Original papers with language:    %d\n", sum(!is.na(flora_augmented$language_o), na.rm = TRUE)))
cat(sprintf("  Replication papers with language: %d\n", sum(!is.na(flora_augmented$language_r), na.rm = TRUE)))

# ---- Step 9b: Classify Replication Intent ----
cat("\n### Step 9b: Classifying replication intent via LLM\n")
cat("  (Only applied to COS data; FLORA and SCORE entries are pre-screened)\n")

cos_rows     <- flora_augmented %>% filter(source == "COS")
non_cos_rows <- flora_augmented %>% filter(source != "COS")
cat(sprintf("  COS rows to classify:          %d\n", nrow(cos_rows)))
cat(sprintf("  Pre-screened rows (FLORA/SCORE): %d\n", nrow(non_cos_rows)))

dois_needing_abstract <- cos_rows %>%
  filter(!is.na(doi_r), is.na(abstract_r) | abstract_r == "") %>%
  pull(doi_r) %>% unique()

if (length(dois_needing_abstract) > 0) {
  cat(sprintf("Fetching abstracts for %d replication DOIs from OpenAlex...\n", length(dois_needing_abstract)))
  openalex_abstracts <- get_openalex_abstracts(dois_needing_abstract, mailto = openalex_mailto)
  openalex_abstracts <- openalex_abstracts[!is.na(openalex_abstracts$doi), ]
  cos_rows <- cos_rows %>%
    left_join(openalex_abstracts %>% rename(doi_r = doi, abstract_r_oa = abstract), by = "doi_r") %>%
    mutate(abstract_r = coalesce(abstract_r, abstract_r_oa)) %>%
    select(-abstract_r_oa)
  cos_rows <- clean_flora_text_fields(cos_rows, verbose = FALSE)
  cat(sprintf("  Abstracts now available for %d / %d COS rows\n",
              sum(!is.na(cos_rows$abstract_r) & cos_rows$abstract_r != ""), nrow(cos_rows)))
}

cos_rows <- classify_replication_intent(cos_rows)
non_cos_rows <- non_cos_rows %>%
  mutate(
    self_identified_replication   = TRUE,
    replication_intent_confidence = "high",
    replication_intent_reasoning  = "Pre-screened source"
  )

flora_augmented <- bind_rows(cos_rows, non_cos_rows)
cat(sprintf("  Self-identified replications: %d\n", sum(flora_augmented$self_identified_replication == TRUE,  na.rm = TRUE)))
cat(sprintf("  Not self-identified:          %d\n", sum(flora_augmented$self_identified_replication == FALSE, na.rm = TRUE)))
cat(sprintf("  Unclassified:                 %d\n", sum(is.na(flora_augmented$self_identified_replication))))
cat(sprintf("  Confidence breakdown: high=%d, medium=%d, low=%d\n",
            sum(flora_augmented$replication_intent_confidence == "high",   na.rm = TRUE),
            sum(flora_augmented$replication_intent_confidence == "medium", na.rm = TRUE),
            sum(flora_augmented$replication_intent_confidence == "low",    na.rm = TRUE)))

# ---- Step 9c: Add Open Access URLs from Unpaywall ----
cat("\n### Step 9c: Adding Open Access URLs from Unpaywall\n")
all_dois <- unique(c(flora_augmented$doi_o, flora_augmented$doi_r))
all_dois <- all_dois[!is.na(all_dois) & nzchar(all_dois)]
cat(sprintf("Looking up %d unique DOIs in Unpaywall...\n", length(all_dois)))

unpaywall_email <- Sys.getenv("OPENALEX_MAILTO", "lukas.wallrich@gmail.com")
oa_results <- get_unpaywall_oa(all_dois, email = unpaywall_email)

flora_augmented <- flora_augmented %>%
  left_join(oa_results %>% rename(doi_o = doi, oa_url_o = oa_url), by = "doi_o") %>%
  left_join(oa_results %>% rename(doi_r = doi, oa_url_r = oa_url), by = "doi_r")

cat(sprintf("  Original papers with OA URL:    %d\n", sum(!is.na(flora_augmented$oa_url_o) & nzchar(flora_augmented$oa_url_o))))
cat(sprintf("  Replication papers with OA URL: %d\n", sum(!is.na(flora_augmented$oa_url_r) & nzchar(flora_augmented$oa_url_r))))

# ---- Step 9d: Annotate meta-paper references ----
cat("\n### Step 9d: Annotating meta-paper references\n")
meta_paper_dois <- tolower(c(
  "10.1038/s41562-024-02062-9",
  "10.3389/fcomm.2022.1048896",
  "10.1073/pnas.2103313118",
  "10.1007/s13164-018-0400-9",
  "10.1038/s41562-018-0399-z",
  "10.1098/rsos.231240",
  "10.1027/1864-9335/a000178",
  "10.1177/2515245918810225",
  "10.1016/j.jesp.2015.10.012",
  "10.1126/science.aac4716",
  "10.1177/08902070221094216",
  "10.1126/science.aaf0918"
))

candidate_meta <- flora_augmented %>%
  filter(!is.na(doi_r), !is.na(url_r), nzchar(url_r)) %>%
  group_by(doi_r) %>%
  summarise(n_urls = n_distinct(url_r), .groups = "drop") %>%
  filter(n_urls >= 5, !tolower(doi_r) %in% meta_paper_dois)
if (nrow(candidate_meta) > 0) {
  cat(sprintf("⚠ WARNING: %d DOIs have >=5 distinct url_r but are not in meta_paper_dois list.\n", nrow(candidate_meta)))
  for (i in seq_len(nrow(candidate_meta)))
    cat(sprintf("    %s (%d distinct urls)\n", candidate_meta$doi_r[i], candidate_meta$n_urls[i]))
}
cat(sprintf("  Known meta-papers: %d\n", length(meta_paper_dois)))

is_meta     <- tolower(flora_augmented$doi_r) %in% meta_paper_dois
has_url     <- !is.na(flora_augmented$url_r) & nzchar(flora_augmented$url_r)
to_annotate <- is_meta & has_url

flora_augmented <- flora_augmented %>%
  mutate(
    ref_r = if_else(
      to_annotate & !grepl("Individual report available at", ref_r, fixed = TRUE),
      paste0(ref_r, " Individual report available at ", url_r), ref_r
    ),
    ref_r_clean = if_else(
      to_annotate & !is.na(ref_r_clean) & !grepl("Individual report available at", ref_r_clean, fixed = TRUE),
      paste0(ref_r_clean, " Individual report available at ", url_r), ref_r_clean
    )
  )
cat(sprintf("  Rows annotated with individual report URL: %d\n", sum(to_annotate)))

# ╔══════════════════════════════════════════════════════════════════╗
# ║  [NEW ANALYSIS]  Validated-CSV Source Report                    ║
# ║                                                                  ║
# ║  Runs before Step 10 because validated_db_row is not in         ║
# ║  output_cols and gets dropped at the output formatting step.    ║
# ╚══════════════════════════════════════════════════════════════════╝
cat("\n### Validated-CSV Source Analysis\n")

if ("validated_db_row" %in% names(flora_augmented)) {

  db_rows <- flora_augmented %>% filter(validated_db_row == TRUE)
  n_db    <- nrow(db_rows)
  n_total <- nrow(flora_augmented)

  cat(sprintf("Records from validated CSV in augmented set: %d / %d (%.1f%%)\n",
              n_db, n_total, 100 * n_db / max(n_total, 1)))

  if (n_db > 0) {

    cat("\n── Breakdown by type ──────────────────────────────────────\n")
    print(table(db_rows$type, useNA = "ifany"))

    cat("\n── Breakdown by outcome ───────────────────────────────────\n")
    print(table(db_rows$outcome, useNA = "ifany"))

    cat("\n── Breakdown by pipeline source ───────────────────────────\n")
    print(table(db_rows$source, useNA = "ifany"))

    cat("\n── Reference coverage after OpenAlex enrichment ───────────\n")
    cat(sprintf("  APA ref_o  filled:  %d / %d (%.0f%%)\n",
                count_present(db_rows$ref_o_clean), n_db,
                100 * count_present(db_rows$ref_o_clean) / n_db))
    cat(sprintf("  APA ref_r  filled:  %d / %d (%.0f%%)\n",
                count_present(db_rows$ref_r_clean), n_db,
                100 * count_present(db_rows$ref_r_clean) / n_db))
    cat(sprintf("  BibTeX ref_o:       %d / %d (%.0f%%)\n",
                count_present(db_rows$bibtex_o), n_db,
                100 * count_present(db_rows$bibtex_o) / n_db))
    cat(sprintf("  BibTeX ref_r:       %d / %d (%.0f%%)\n",
                count_present(db_rows$bibtex_r), n_db,
                100 * count_present(db_rows$bibtex_r) / n_db))
    cat(sprintf("  title_o present:    %d / %d\n", count_present(db_rows$title_o), n_db))
    cat(sprintf("  title_r present:    %d / %d\n", count_present(db_rows$title_r), n_db))

    cat("\n── Identifier coverage ────────────────────────────────────\n")
    cat(sprintf("  doi_o present:      %d / %d\n", count_present(db_rows$doi_o), n_db))
    cat(sprintf("  doi_r present:      %d / %d\n", count_present(db_rows$doi_r), n_db))
    cat(sprintf("  url_r present:      %d / %d\n", count_present(db_rows$url_r), n_db))

    cat("\n── Enrichment coverage ────────────────────────────────────\n")
    cat(sprintf("  Language (orig):    %d / %d\n", count_present(db_rows$language_o), n_db))
    cat(sprintf("  Language (repl):    %d / %d\n", count_present(db_rows$language_r), n_db))
    if ("oa_url_o" %in% names(db_rows))
      cat(sprintf("  OA URL (orig):      %d / %d\n", count_present(db_rows$oa_url_o), n_db))
    if ("oa_url_r" %in% names(db_rows))
      cat(sprintf("  OA URL (repl):      %d / %d\n", count_present(db_rows$oa_url_r), n_db))

    cat("\n── Replication intent (LLM classification) ────────────────\n")
    if ("self_identified_replication" %in% names(db_rows)) {
      cat(sprintf("  Self-identified:     %d\n", sum(db_rows$self_identified_replication == TRUE,  na.rm = TRUE)))
      cat(sprintf("  Not self-identified: %d\n", sum(db_rows$self_identified_replication == FALSE, na.rm = TRUE)))
      cat(sprintf("  Unclassified:        %d\n", sum(is.na(db_rows$self_identified_replication))))
    }

  } else {
    cat("  No validated-CSV rows found in the augmented dataset.\n")
  }

} else {
  cat("  validated_db_row column not found — CSV merge was likely skipped.\n")
}

# ---- Step 10: Format for Output ----
cat("\n### Step 10: Formatting for output\n")
output_cols <- c(
  "doi_o", "doi_o_alt", "doi_o_hash", "title_o", "author_o", "journal_o", "year_o",
  "volume_o", "issue_o", "pages_o", "apa_ref_o", "bibtex_ref_o", "url_o", "language_o",
  "doi_r", "doi_r_alt", "doi_r_hash", "title_r", "author_r", "journal_r", "year_r",
  "volume_r", "issue_r", "pages_r", "apa_ref_r", "bibtex_ref_r", "url_r", "language_r",
  "oa_url_o", "oa_url_r",
  "outcome", "outcome_quote", "outcome_quote_source", "type", "source",
  "self_identified_replication", "replication_intent_confidence"
)

flora_renames <- c(apa_ref_o = "ref_o_clean", apa_ref_r = "ref_r_clean",
                   bibtex_ref_o = "bibtex_o",  bibtex_ref_r = "bibtex_r")
flora_augmented <- flora_augmented %>% rename(!!!flora_renames)

available_output <- intersect(output_cols, names(flora_augmented))
flora_all <- flora_augmented %>% select(all_of(available_output))
flora_all <- strip_dummy_dois(flora_all, verbose = TRUE)

excluded_rows <- flora_all %>%
  filter(is.na(title_o) | title_o == "" | is.na(title_r) | title_r == "") %>%
  mutate(reason = case_when(
    (is.na(title_o) | title_o == "") & (is.na(title_r) | title_r == "") ~ "missing both title_o and title_r",
    is.na(title_o) | title_o == "" ~ "missing title_o",
    is.na(title_r) | title_r == "" ~ "missing title_r"
  )) %>%
  select(reason, source, doi_o, apa_ref_o, doi_r, url_r, apa_ref_r)

if (nrow(excluded_rows) > 0) {
  export_log_path <- here::here("output", "flora_export_log.csv")
  write_excel_csv(excluded_rows, export_log_path)
  cat(sprintf("⚠ %d rows excluded due to missing reference details\n", nrow(excluded_rows)))
  cat(sprintf("  Export log saved to: %s\n", export_log_path))
} else {
  cat("✓ No rows excluded due to missing reference details\n")
}

flora_final <- flora_all %>%
  filter(!is.na(title_o), title_o != "", !is.na(title_r), title_r != "")

n_non_repl <- sum(flora_final$self_identified_replication == FALSE, na.rm = TRUE)
if (n_non_repl > 0) cat(sprintf("⚠ %d rows removed: not self-identified as replications\n", n_non_repl))

flora_final <- flora_final %>%
  filter(self_identified_replication == TRUE | is.na(self_identified_replication))

cat(sprintf("✓ Formatted for output\n"))
cat(sprintf("  Final columns: %d\n", ncol(flora_final)))
cat(sprintf("  Final rows:    %d\n", nrow(flora_final)))

# ---- Step 11: Save Output ----
cat("\n### Step 11: Saving output\n")
if (!dir.exists(here::here("output"))) dir.create(here::here("output"))

write_excel_csv(flora_final, FLORA_OUTPUT)
cat(sprintf("✓ Saved to: %s\n", FLORA_OUTPUT))
cat(sprintf("  Format: CSV (UTF-8)\n"))
cat(sprintf("  Rows: %d (Replications + Reproductions)\n", nrow(flora_final)))
cat(sprintf("  Columns: %d\n", ncol(flora_final)))

cat("\n### Summary Statistics\n")
cat(sprintf("Total paper pairs: %d\n", nrow(flora_final)))
if ("type"        %in% names(flora_final)) { cat("\nRows by type:\n"); print(table(flora_final$type, useNA = "ifany")) }
if ("outcome"     %in% names(flora_final)) cat(sprintf("Rows with outcome codes: %d\n",                              sum(has_text(flora_final$outcome))))
if ("apa_ref_o"   %in% names(flora_final)) cat(sprintf("Original papers with APA reference: %d\n",                  sum(has_text(flora_final$apa_ref_o))))
if ("apa_ref_r"   %in% names(flora_final)) cat(sprintf("Replication/reproduction papers with APA reference: %d\n",  sum(has_text(flora_final$apa_ref_r))))
if ("bibtex_ref_o" %in% names(flora_final)) cat(sprintf("Original papers with BibTeX: %d\n",                        sum(has_text(flora_final$bibtex_ref_o))))
if ("bibtex_ref_r" %in% names(flora_final)) cat(sprintf("Replication/reproduction papers with BibTeX: %d\n",        sum(has_text(flora_final$bibtex_ref_r))))
if ("language_o"  %in% names(flora_final)) cat(sprintf("Original papers with language metadata: %d\n",              sum(has_text(flora_final$language_o))))
if ("language_r"  %in% names(flora_final)) cat(sprintf("Replication papers with language metadata: %d\n",           sum(has_text(flora_final$language_r))))
if ("doi_o"       %in% names(flora_final)) cat(sprintf("Rows with original DOI: %d\n",                              sum(has_text(flora_final$doi_o))))
if ("doi_r"       %in% names(flora_final)) cat(sprintf("Rows with replication/reproduction DOI: %d\n",              sum(has_text(flora_final$doi_r))))

# ---- Pipeline Complete ----
cat("\n=== FLoRA Preparation Pipeline Complete ===\n")
cat("(Includes both Replications and Reproductions)\n")
cat(sprintf("Completion time: %s\n", format(Sys.time(), "%Y-%m-%d %H:%M:%S")))
cat(sprintf("Output file: %s\n", FLORA_OUTPUT))
cat("\nNext steps:\n")
cat("1. Review the generated flora.csv file\n")
cat("2. Optionally: pipelines/flora/release_flora.qmd to release to OSF\n")
